FROM node:20.12.2

RUN apt-get update && apt-get install -y --no-install-recommends make=4.3-4.1 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Отключаем интерактивные запросы
ENV CI=true

# Копируем манифесты зависимостей
COPY app/package.json ./package.json
COPY app/package-lock.json ./package-lock.json

# Устанавливаем зависимости
RUN npm ci

# Копируем исходный код
COPY app/. .

EXPOSE 8080
ENV NODE_ENV=production

# Собираем проект
RUN make build

CMD ["make", "start"]